#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-googledrive
Version  : 1.0.1
Release  : 1
URL      : https://cran.r-project.org/src/contrib/googledrive_1.0.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/googledrive_1.0.1.tar.gz
Summary  : An Interface to Google Drive
Group    : Development/Tools
License  : MIT
Requires: R-curl
Requires: R-glue
Requires: R-httr
Requires: R-jsonlite
Requires: R-magrittr
Requires: R-purrr
Requires: R-rlang
Requires: R-tibble
Requires: R-uuid
BuildRequires : R-curl
BuildRequires : R-gargle
BuildRequires : R-glue
BuildRequires : R-httr
BuildRequires : R-jsonlite
BuildRequires : R-magrittr
BuildRequires : R-purrr
BuildRequires : R-rlang
BuildRequires : R-tibble
BuildRequires : R-uuid
BuildRequires : buildreq-R

%description
# googledrive <img src="man/figures/logo.png" align="right" height=140/>
[![CRAN\_Status\_Badge](http://www.r-pkg.org/badges/version/googledrive)](https://cran.r-project.org/package=googledrive)
[![Build
Status](https://travis-ci.org/tidyverse/googledrive.svg?branch=master)](https://travis-ci.org/tidyverse/googledrive)[![AppVeyor
Build
Status](https://ci.appveyor.com/api/projects/status/github/tidyverse/googledrive?branch=master&svg=true)](https://ci.appveyor.com/project/tidyverse/googledrive)[![codecov](https://codecov.io/gh/tidyverse/googledrive/branch/master/graph/badge.svg)](https://codecov.io/gh/tidyverse/googledrive?branch=master)

%prep
%setup -q -c -n googledrive
cd %{_builddir}/googledrive

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1620235392

%install
export SOURCE_DATE_EPOCH=1620235392
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library googledrive
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library googledrive
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library googledrive
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc googledrive || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/googledrive/DESCRIPTION
/usr/lib64/R/library/googledrive/INDEX
/usr/lib64/R/library/googledrive/LICENSE
/usr/lib64/R/library/googledrive/Meta/Rd.rds
/usr/lib64/R/library/googledrive/Meta/features.rds
/usr/lib64/R/library/googledrive/Meta/hsearch.rds
/usr/lib64/R/library/googledrive/Meta/links.rds
/usr/lib64/R/library/googledrive/Meta/nsInfo.rds
/usr/lib64/R/library/googledrive/Meta/package.rds
/usr/lib64/R/library/googledrive/Meta/vignette.rds
/usr/lib64/R/library/googledrive/NAMESPACE
/usr/lib64/R/library/googledrive/NEWS.md
/usr/lib64/R/library/googledrive/R/googledrive
/usr/lib64/R/library/googledrive/R/googledrive.rdb
/usr/lib64/R/library/googledrive/R/googledrive.rdx
/usr/lib64/R/library/googledrive/R/sysdata.rdb
/usr/lib64/R/library/googledrive/R/sysdata.rdx
/usr/lib64/R/library/googledrive/WORDLIST
/usr/lib64/R/library/googledrive/doc/googledrive.Rmd
/usr/lib64/R/library/googledrive/doc/googledrive.html
/usr/lib64/R/library/googledrive/doc/index.html
/usr/lib64/R/library/googledrive/extdata/chicken.csv
/usr/lib64/R/library/googledrive/extdata/chicken.jpg
/usr/lib64/R/library/googledrive/extdata/chicken.pdf
/usr/lib64/R/library/googledrive/extdata/chicken.txt
/usr/lib64/R/library/googledrive/extdata/files_fields.csv
/usr/lib64/R/library/googledrive/extdata/mime_tbl.csv
/usr/lib64/R/library/googledrive/extdata/translate_mime_types.csv
/usr/lib64/R/library/googledrive/help/AnIndex
/usr/lib64/R/library/googledrive/help/aliases.rds
/usr/lib64/R/library/googledrive/help/figures/logo.png
/usr/lib64/R/library/googledrive/help/googledrive.rdb
/usr/lib64/R/library/googledrive/help/googledrive.rdx
/usr/lib64/R/library/googledrive/help/paths.rds
/usr/lib64/R/library/googledrive/html/00Index.html
/usr/lib64/R/library/googledrive/html/R.css
/usr/lib64/R/library/googledrive/secret/googledrive-docs.json
/usr/lib64/R/library/googledrive/secret/googledrive-testing.json
/usr/lib64/R/library/googledrive/tests/spelling.R
/usr/lib64/R/library/googledrive/tests/testthat.R
/usr/lib64/R/library/googledrive/tests/testthat/all-test-clean.R
/usr/lib64/R/library/googledrive/tests/testthat/all-test-setup.R
/usr/lib64/R/library/googledrive/tests/testthat/all-test-setup.html
/usr/lib64/R/library/googledrive/tests/testthat/driver.R
/usr/lib64/R/library/googledrive/tests/testthat/helper.R
/usr/lib64/R/library/googledrive/tests/testthat/setup-testing.R
/usr/lib64/R/library/googledrive/tests/testthat/test-as_id.R
/usr/lib64/R/library/googledrive/tests/testthat/test-dplyr-compatibility.R
/usr/lib64/R/library/googledrive/tests/testthat/test-dribble-class.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_auth.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_cp.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_create.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_download.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_endpoints.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_fields.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_find.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_get.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_link.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_ls.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_mime_type.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_mv.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_publish.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_put.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_rm.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_share.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_trash.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_update.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_upload.R
/usr/lib64/R/library/googledrive/tests/testthat/test-drive_user.R
/usr/lib64/R/library/googledrive/tests/testthat/test-files/client_secret_123.googleusercontent.com.json
/usr/lib64/R/library/googledrive/tests/testthat/test-files/just_a_dribble.rds
/usr/lib64/R/library/googledrive/tests/testthat/test-files/mix_of_files_and_teamdrives.rds
/usr/lib64/R/library/googledrive/tests/testthat/test-generate_request.R
/usr/lib64/R/library/googledrive/tests/testthat/test-path-utils.R
/usr/lib64/R/library/googledrive/tests/testthat/test-pathification.R
/usr/lib64/R/library/googledrive/tests/testthat/test-team_drive_params.R
/usr/lib64/R/library/googledrive/tests/testthat/test-tree-climbing.R
/usr/lib64/R/library/googledrive/tests/testthat/test-utils.R
/usr/lib64/R/library/googledrive/tests/testthat/testing-token.rds
